export default {
  data() {
    return {
      alarmDataTotal: {
        // 普通报警
        alarmInput: 'alarmInput',
        alarmZone: 'alarmZone',
        alarmGT: 'alarmGT',
        // 智能报警
        perimeter: 'perimeter',
        tripwire: 'tripwire',
        leftObject: 'leftObject',
        missingObject: 'missingObject',
        loitering: 'loitering',
        retrogradeDetection: 'retrogradeDetection',
        lingerDetection: 'lingerDetection',
        doubleCordon: 'doubleCordon',
        blackList: 'blackList',
        whiteList: 'whiteList',
        dispatch: 'dispatch',
        areaInvade: 'areaInvade',
        fastMove: 'fastMove',
        parkDetect: 'parkDetect',
        humanAssemble: 'humanAssemble',
        objectMove: 'objectMove',
        // 违章报警
        vioRetrograde: 'vioRetrograde',
        vioPark: 'vioPark',
        vioTurnLeft: 'vioTurnLeft',
        vioTurnRight: 'vioTurnRight',
        // 人像布控
        faceControl: 'faceControl',
        // 监控点报警报警
        alarmMoveSense: 'alarmMoveSense',
        videoMask: 'videoMask',
        sceneSwitch: 'sceneSwitch',
        definitionAbnormal: 'definitionAbnormal',
        brightnessAbnormal: 'brightnessAbnormal',
        screenFreeze: 'screenFreeze',
        noise: 'noise',
        signalLoss: 'signalLoss',
        colorCast: 'colorCast',
        // 重点关注
        focusAttention: 'focusAttention',
        // 报警求助
        askHelp: 'askHelp',
        acceptHelp: 'acceptHelp',
        endHelp: 'endHelp',
        // 消防报警
        fireAlarm: 'fireAlarm',
        // 单兵报警
        individualAlarm: 'individualAlarm',
        // 巡更报警
        patrolAlarm: 'patrolAlarm',
        // 手工报警
        manualAlarm: 'manualAlarm'
      },
      alarmSort: {
        // 普通报警
        helpSeek: '报警输入',
        alarmInput: '报警输入',
        alarmZone: '报警防区',
        alarmGT: '报警防区',
        perimeterAlarm: '报警防区',
        intrusionAlarm: '报警防区',
        electricFence: '报警防区',
        // 智能报警
        perimeter: '智能报警',
        tripwire: '智能报警',
        leftObject: '智能报警',
        missingObject: '智能报警',
        loitering: '智能报警',
        retrogradeDetection: '智能报警',
        lingerDetection: '智能报警',
        doubleCordon: '智能报警',
        blackList: '智能报警',
        whiteList: '智能报警',
        dispatch: '智能报警',
        areaInvade: '智能报警',
        fastMove: '智能报警',
        parkDetect: '智能报警',
        humanAssemble: '智能报警',
        objectMove: '智能报警',
        // 违章报警
        vioRetrograde: '违章报警',
        vioPark: '违章报警',
        vioTurnLeft: '违章报警',
        vioTurnRight: '违章报警',
        // 人像布控
        faceControl: '人像布控',
        // 监控点报警
        alarmMoveSense: '监控点报警',
        videoMask: '监控点报警',
        sceneSwitch: '监控点报警',
        definitionAbnormal: '监控点报警',
        brightnessAbnormal: '监控点报警',
        screenFreeze: '监控点报警',
        noise: '监控点报警',
        signalLoss: '监控点报警',
        colorCast: '监控点报警',
        // 重点关注
        focusAttention: '重点关注',
        // 报警求助
        askHelp: '报警求助',
        acceptHelp: '报警求助',
        endHelp: '报警求助',
        // 消防报警
        fireAlarm: '消防报警',
        smoke: '消防报警',
        temperature: '消防报警',
        hydrant: '消防报警',
        handNewspaper: '消防报警',
        // 单兵报警
        individualAlarm: '单兵一键报警',
        // 巡更报警
        patrolAlarm: '巡更异常上报',
        // 手工报警
        manualAlarm: '手工报警'
      },
      equipmentDataTotal: {
        sdCardFailure: 'sdCardFailure',
        sdCardFull: 'sdCardFull',
        networkDown: 'networkDown',
        ipConflict: 'ipConflict',
        timeAbnormal: 'timeAbnormal',
        illegalNetworkAccess: 'illegalNetworkAccess'
      },
      equipmentSort: {
        sdCardFailure: '设备报警',
        sdCardFull: '设备报警',
        networkDown: '设备报警',
        ipConflict: '设备报警',
        timeAbnormal: '设备报警',
        illegalNetworkAccess: '设备报警'
      }
    }
  }
}
